# this is my bash_aliases file
alias cdd='cd ..'
alias gomoos='cd ~/Downloads/C++/moos-ivp'
alias nembs='emacs -nw ~/.bashrc; source ~/.bashrc'
alias mm='cd ~/my_cpp_files/; make; cd -'
alias goc='cd /mnt/Users'
alias testmoossvn='svn co svn+ssh://oceanai.mit.edu/home/svn/repos/moos-ivp-kfung'
alias gobuild='cd ~/Downloads/C++/moos-ivp-kfung;./build.sh;cd -'
alias gokmoos='cd ~/Downloads/C++/moos-ivp-kfung'
alias gopri='cd ~/Downloads/C++/moos-ivp-kfung/src/pPrimeFactor'
alias gomispri='cd ~/Downloads/C++/moos-ivp-kfung/missions/prime_factors'
alias empri='emacs ~/Downloads/C++/moos-ivp-kfung/missions/prime_factors/prime.moos'
alias testpri='pAntler ~/Downloads/C++/moos-ivp-kfung/missions/prime_factors/prime.moos'
alias testbigpri='pAntler ~/Downloads/C++/moos-ivp-kfung/missions/prime_factors/bigprime.moos'
alias svnreport='svn update; svn log'
